redis:
  restart: always
  image: redis:latest
  command: redis-server --appendonly yes
  volumes_from:
    - storage

storage:
  restart: always
  image: busybox:latest
  volumes:
    - /var/lib/redis:/data
  
hubot:
  restart: always
  build: .
  ports:
    - '8190:8080'
  environment:
    REDIS_URL: redis://redis:6379
    HUBOT_NAME: 'cwbot'
    HUBOT_ALIAS:
    HUBOT_CHATWORK_TOKEN: 
    HUBOT_CHATWORK_ROOMS: 
    HUBOT_CHATWORK_API_RATE: 420
  links:
    - redis
